before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: 0a91mzPGn9GQz0uwg9gAqV6P5ZAmepo5bNXpa38VxvWmTuFIaOn8ukJqvkjgg5tnOXdHcFFpnprjJ8+LsWswRL53pBtvkUtOs9mQ82yfUPEx3OmjpQyy0thEK+Fb0OEagq1k5Hj3yBQIS5vDR+ZcZW456+18T+PxRq6DcVuVk3rHIWS0efaLX7y3/4ffkr+XPn8Hv+L27jOBUx3JKEBZ+jhJ6/7nYC9idbw0U0BwilQtmKQg9T3M5PeFPmwfK++F156BNZYOqpwvX+LPalrtSMuuY9ZRiSQ2+x8hUbD/4KxczpGhUFLxStVPIRmyJU76ENvl6LT8eWx0iOn8QFEPzCTOu5xoeSFfk6CEpa3V4Vdianv7w50MpzEtjzujlvyyZrpl8xN8tbnn+XBhBIgNwNs/+NSUZltQ+mN8T4sluQZmDFXaH0PV4nLzLn70VTDZxvf23qWudjB9nkLHJa74UJq6SL1fhGGKonoSHMyaulxWd+6OJbxtM8u4sYSJPvi3Gsrrka9OgxQrW/N/K4hbLd08eWpzfMTTLP/j4hn+XyTdsvu3/PP0H+utUO4hM19q+jvK7haMPEVyzFmQqpc5Nhz4Z4/xGlR+MZISyshXBtdQ8ZHRRsV8YWXBuByrafz196fF/yD9f+KfNHT8yzRQuG+myTsZcQOHcReD42CzWpY= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
